# Site settings
baseURL = "https://cancerandcrossfit.com"
languageCode = "en-US"
title = "Cancer and Crossfit"
theme = "hugo-split-theme"
disableKinds = [ "taxonomy", "taxonomyTerm"  ]
enableRobotsTXT = true

[contentTypes]
  [contentTypes.episode]
  name = "episodes"
  plural = "episodes"
  singular = "episode"
  layout = "layouts/episode"

# Local preview mode
relativeURLs = true
uglyURLs = true

# Enter your tracking code to enable Google Analytics
googleAnalytics = "G-B69FM01F7W"

# Copyright
copyright = "&copy;2023 Cancer and Crossfit:&nbsp; <a href=\"mailto:podcast@cancerandcrossfit.com\">podcast@cancerandcrossfit.com</a><p>"

[params]

  # Metadata for search engines and social sharing
  author = "Krystal & Rich"
  description = "Cancer And Crossfit is a podcast discussing cancer, exercise as a form of symptom management, end of life care.  We attempt to break down stigma around cancer, death, dying and day-to-day living.  Crossfit is our exercise regimen of choice, but we have no direct connection to Crossfit, LLC."
  shareImage = "images/social.jpg"
  twitterHandle = "onepagelove"

  # Favicon
  [params.favico]
  # Tile color for MS browsers, eg:
  # browserconfig.xml
  tile_color = "#DA532C"

  # Section - Visual
  [params.visual]

    # Image
    [params.visual.image]
      enable = true
      file = "Logo.svg"
#      position = "center center"

    # Video
    [params.visual.video]
      enable = false
      mute = true
      file = "/videos/square-out.mp4"
#      youtubeId = "Hd_ptbiPoXM"

  # Links
  #
  # Links List #1
  [[params.links]]
    [params.links.list1]
      heading = "Podcast Links"

      [[params.links.list1.link]]
        text = "Apple Music"
        url = "https://podcasts.apple.com/us/podcast/cancer-and-crossfit/id1700042264"
        new_tab = true # new tab

      [[params.links.list1.link]]
        text = "Spotify"
        url = "https://open.spotify.com/show/2rhy4IR1lz3ZGeGTtnqotR"
        new_tab = true # Default, open at same tab

      [[params.links.list1.link]]
        text = "iHeart Radio"
        url = "https://www.iheart.com/podcast/269-cancer-and-crossfit-119852051/"

  # Links List #2
  [[params.links]]
    [params.links.list2]
      heading = "More Podcast links"

      [[params.links.list2.link]]
        text = "Google Podcasts"
        url = "https://podcasts.google.com/feed/aHR0cHM6Ly9hbmNob3IuZm0vcy9lNjg5MmE4OC9wb2RjYXN0L3Jzcw"
        new_tab = true

      [[params.links.list2.link]]
        text = "Amazon Music"
        url = "https://music.amazon.com/podcasts/03eb3512-e5e7-4c99-a42d-665cb36ad77c/cancer-and-crossfit"
        new_tab = true

      [[params.links.list2.link]]
        text = "Castbox"
        url = "https://castbox.fm/channel/id5534292"
        new_tab = true

  # Links List #3
  [[params.links]]
    [params.links.list3]
      heading = "Socials"

      [[params.links.list3.link]]
        text = "Krystal"
        url = "https://instagram.com/cancerandcrossfit"

      [[params.links.list3.link]]
        text = "Rich"
        url = "https://richardhorwood.com/"

      [[params.links.list3.link]]
        text = "CFCP"
        url = "https://instagram.com/crossfitchirnsidepark"

  # The original template is released under the Creative Commons Attribution 3.0 License.
  # Please keep the original attribution link when using for your own project.
  # If you'd like to use the template without the attribution, you can check out
  # the license option via the template author's website: https://onepagelove.com/split
